server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
#    container-name

# the cloud inside spring is used to configure the gateway route through Eureka
# the CUSTOMER is the name of instance inside Eureka
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      #    container-name


